[phases.setup]
required = ["python39"]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
nixPkgs = ["poppler_utils"]
commands = ["pip install -r requirements.txt"]

[phases.build]
commands = ["echo 'Building Python backend only'"]

[start]
command = "python app.py"
